sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run react-test npm test -- --coverage
  
after_success:
  - docker build -t docker-testing/multi-client -f ./client
  - docker build -t docker-testing/multi-nginx -f ./nginx
  - docker build -t docker-testing/multi-server -f ./server
  - docker build -t docker-testing/multi-worker -f ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push multi-client
  - docker push nginx
  - docker push server
  - docker push worker


