sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run react-test npm test -- --coverage
  
after_success:
  - docker build -t timcast/docker-testing:multi-client ./client
  - docker build -t timcast/docker-testing:multi-nginx ./nginx
  - docker build -t timcast/docker-testing:multi-server ./server
  - docker build -t timcast/docker-testing:multi-worker ./worker
  # Log in to the docker CLI
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  # Take those images and push them to docker hub
  - docker push timcast/docker-testing:multi-client
  - docker push timcast/docker-testing:multi-nginx
  - docker push timcast/docker-testing:multi-server
  - docker push timcast/docker-testing:multi-worker


